# ||||||||||        ||         ||
# |         \       | |       | |
# |         |       |  |     |  |
# |         |       |   |   |   |
# |         /       |    | |    |
# |        /        |     |     |
# |||||||||         |           |
# |        \        |           |
# |         |       |           |
# |         |       |           |
# |        /        |           |
# ||||||||/  etter  |           |OTD

# BetterMOTD will replace certain character combinations with other words.
# &p will be replaced with the sender's name.
# &w will be replaced with the world the sender is in.
# &s will be replaced with the server the sender is on.
# Color codes to match those of essential's are available at http://bit.ly/mccolours

MOTD: Welcome,  &4&p&r! You are in world &w, and on server &s!

# Since the getServer() string will display CraftBukkit instead of your server name, I had
# to replace it with this getString().
# in other words, this string is required to be able to use &s, however used or not this
# may not be NOT. NOT. Be blank
serverName: (server name here)
